### Boston Housing Dataset

In [2]:
import numpy as np
import pandas as pd

In [4]:
URL = "https://raw.githubusercontent.com/ProfAI/machine-learning-fondamenti/main/datasets/housing_dirty.csv"

- Verifica il numero di righe e colonne del dataset
- Verifica la tipologia di ogni variabile
- Verifica il numero di valori mancanti per ogni colonna
- Rimuovi eventualmente le colonne con oltre il 30% di valori mancanti
- Rimuovi eventualmente le righe con oltre il 25% di valori mancanti
- Rimuovi tutte le righe dove PRICE è mancante
- Esegui l'imputazione con valore medio per i restanti valori mancanti quantitativi
- Esegui la codifica di eventuali variabili qualitative
- Esegui l'imputazione con moda per i restanti valori mancanti qualitativi
- Esegui la standardizzazione
- Salva il nuovo dataframe in un tsv chiamato "housing_clean.tsv"

In [5]:
df = pd.read_csv(URL)
df.head(10)

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0,0.0,LOW,18.0,2.31,NO,538.0,6575.00,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,1.0,LOW,0.0,7.07,NO,469.0,6421.00,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,2.0,LOW,0.0,7.07,NO,469.0,7185.00,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,3.0,LOW,0.0,2.18,NO,458.0,6998.00,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,4.0,LOW,0.0,2.18,NO,458.0,7147.00,54.2,6.0622,3.0,222.0,18.7,396.90,NaN,36.2
5,5.0,LOW,0.0,2.18,NO,458.0,6.43,58.7,6.0622,3.0,222.0,18.7,394.12,NaN,28.7
6,6.0,MODERATE,12.5,7.87,NO,524.0,6012.00,66.6,5.5605,5.0,311.0,15.2,395.60,NaN,22.9
7,7.0,MODERATE,12.5,7.87,NO,524.0,6172.00,96.1,5.9505,5.0,311.0,15.2,396.90,NaN,27.1
8,8.0,MODERATE,12.5,7.87,NO,524.0,5631.00,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,16.5
9,9.0,MODERATE,12.5,7.87,NO,524.0,6004.00,85.9,6.5921,5.0,311.0,15.2,386.71,17.10,18.9

In [6]:
df = pd.read_csv(URL, index_col=0)
df.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0.0,LOW,18.0,2.31,NO,538.0,6575.00,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1.0,LOW,0.0,7.07,NO,469.0,6421.00,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2.0,LOW,0.0,7.07,NO,469.0,7185.00,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3.0,LOW,0.0,2.18,NO,458.0,6998.00,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4.0,LOW,0.0,2.18,NO,458.0,7147.00,54.2,6.0622,3.0,222.0,18.7,396.90,NaN,36.2
5.0,LOW,0.0,2.18,NO,458.0,6.43,58.7,6.0622,3.0,222.0,18.7,394.12,NaN,28.7
6.0,MODERATE,12.5,7.87,NO,524.0,6012.00,66.6,5.5605,5.0,311.0,15.2,395.60,NaN,22.9
7.0,MODERATE,12.5,7.87,NO,524.0,6172.00,96.1,5.9505,5.0,311.0,15.2,396.90,NaN,27.1
8.0,MODERATE,12.5,7.87,NO,524.0,5631.00,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,16.5
9.0,MODERATE,12.5,7.87,NO,524.0,6004.00,85.9,6.5921,5.0,311.0,15.2,386.71,17.10,18.9

In [16]:
df.shape

(506, 14)

In [ ]:
df.info() # per capire il tipo di dato

<class 'pandas.DataFrame'>
Index: 506 entries, 0.0 to 505.0
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    str
 1   ZN       504 non-null    float64
 2   INDUS    503 non-null    float64
 3   CHAS     506 non-null    str
 4   NOX      499 non-null    float64
 5   RM       501 non-null    float64
 6   AGE      502 non-null    float64
 7   DIS      501 non-null    float64
 8   RAD      503 non-null    float64
 9   TAX      504 non-null    float64
 10  PTRATIO  501 non-null    float64
 11  B        503 non-null    float64
 12  LSTAT    307 non-null    float64
 13  PRICE    502 non-null    float64
dtypes: float64(12), str(2)
memory usage: 59.3 KB

In [ ]:
df.describe() #per le variabili numeriche

,ZN,INDUS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
count,504.000000,503.000000,499.000000,501.000000,502.000000,501.000000,503.000000,504.000000,501.000000,503.000000,307.000000,502.000000
mean,11.359127,11.165169,464.341474,5635.118064,68.514741,380.588031,9.574553,408.380952,18.463673,356.732127,12.360521,22.479482
std,23.355367,6.870201,223.653453,2007.343355,28.180007,1273.597641,8.725901,168.806575,2.151734,91.405284,7.307171,9.159295
min,0.000000,0.460000,0.400000,4.880000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.000000,5.190000,428.000000,5757.000000,45.025000,2.118500,4.000000,279.000000,17.400000,375.425000,6.545000,16.850000
50%,0.000000,9.690000,504.000000,6129.000000,77.500000,3.495200,5.000000,330.000000,19.100000,391.430000,10.590000,21.200000
75%,12.500000,18.100000,605.000000,6545.000000,93.975000,6.062200,24.000000,666.000000,20.200000,396.220000,17.025000,25.000000
max,100.000000,27.740000,871.000000,8725.000000,100.000000,8344.000000,24.000000,711.000000,22.000000,396.900000,36.980000,50.000000

In [ ]:
df["CRIM"].value_counts() #lo usiamo quando una variabile è categorica, cioè quando non ha valori numerici continui ma etichette o classi

CRIM
HIGH         130
LOW          127
VERY HIGH    127
MODERATE     122
Name: count, dtype: int64

In [10]:
df["CHAS"].value_counts()

CHAS
NO     471
YES     35
Name: count, dtype: int64

In [6]:
df = pd.read_csv(URL).count()
df

Unnamed: 0    506
CRIM          506
ZN            504
INDUS         503
CHAS          506
NOX           499
RM            501
AGE           502
DIS           501
RAD           503
TAX           504
PTRATIO       501
B             503
LSTAT         307
PRICE         502
dtype: int64

In [17]:
df.isna().sum()

CRIM         0
ZN           2
INDUS        3
CHAS         0
NOX          7
RM           5
AGE          4
DIS          5
RAD          3
TAX          2
PTRATIO      5
B            3
LSTAT      199
PRICE        4
dtype: int64

In [20]:
df_drop = df.copy()

In [21]:
df_drop.shape

(506, 14)

In [22]:
tresh = int(df_drop.shape[0]*0.7)
tresh

354

In [23]:
df_drop = df_drop.dropna(axis=1, thresh=354)
df_drop.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,PRICE
0.0,LOW,18.0,2.31,NO,538.0,6575.00,65.2,4.0900,1.0,296.0,15.3,396.90,24.0
1.0,LOW,0.0,7.07,NO,469.0,6421.00,78.9,4.9671,2.0,242.0,17.8,396.90,21.6
2.0,LOW,0.0,7.07,NO,469.0,7185.00,61.1,4.9671,2.0,242.0,17.8,392.83,34.7
3.0,LOW,0.0,2.18,NO,458.0,6998.00,45.8,6.0622,3.0,222.0,18.7,394.63,33.4
4.0,LOW,0.0,2.18,NO,458.0,7147.00,54.2,6.0622,3.0,222.0,18.7,396.90,36.2
5.0,LOW,0.0,2.18,NO,458.0,6.43,58.7,6.0622,3.0,222.0,18.7,394.12,28.7
6.0,MODERATE,12.5,7.87,NO,524.0,6012.00,66.6,5.5605,5.0,311.0,15.2,395.60,22.9
7.0,MODERATE,12.5,7.87,NO,524.0,6172.00,96.1,5.9505,5.0,311.0,15.2,396.90,27.1
8.0,MODERATE,12.5,7.87,NO,524.0,5631.00,100.0,6.0821,5.0,311.0,15.2,386.63,16.5
9.0,MODERATE,12.5,7.87,NO,524.0,6004.00,85.9,6.5921,5.0,311.0,15.2,386.71,18.9

In [24]:
df_drop.shape

(506, 13)

In [25]:
tresh = int(df_drop.shape[1]*0.75)
tresh

9

In [26]:
df_drop = df_drop.dropna(axis=0, thresh=9)
df_drop.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,PRICE
0.0,LOW,18.0,2.31,NO,538.0,6575.00,65.2,4.0900,1.0,296.0,15.3,396.90,24.0
1.0,LOW,0.0,7.07,NO,469.0,6421.00,78.9,4.9671,2.0,242.0,17.8,396.90,21.6
2.0,LOW,0.0,7.07,NO,469.0,7185.00,61.1,4.9671,2.0,242.0,17.8,392.83,34.7
3.0,LOW,0.0,2.18,NO,458.0,6998.00,45.8,6.0622,3.0,222.0,18.7,394.63,33.4
4.0,LOW,0.0,2.18,NO,458.0,7147.00,54.2,6.0622,3.0,222.0,18.7,396.90,36.2
5.0,LOW,0.0,2.18,NO,458.0,6.43,58.7,6.0622,3.0,222.0,18.7,394.12,28.7
6.0,MODERATE,12.5,7.87,NO,524.0,6012.00,66.6,5.5605,5.0,311.0,15.2,395.60,22.9
7.0,MODERATE,12.5,7.87,NO,524.0,6172.00,96.1,5.9505,5.0,311.0,15.2,396.90,27.1
8.0,MODERATE,12.5,7.87,NO,524.0,5631.00,100.0,6.0821,5.0,311.0,15.2,386.63,16.5
9.0,MODERATE,12.5,7.87,NO,524.0,6004.00,85.9,6.5921,5.0,311.0,15.2,386.71,18.9

In [27]:
df_drop.shape

(503, 13)

In [28]:
df_drop = df_drop.dropna(subset = ["PRICE"])
df_drop.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,PRICE
0.0,LOW,18.0,2.31,NO,538.0,6575.0,65.2,4.0900,1.0,296.0,15.3,396.90,24.0
1.0,LOW,0.0,7.07,NO,469.0,6421.0,78.9,4.9671,2.0,242.0,17.8,396.90,21.6
2.0,LOW,0.0,7.07,NO,469.0,7185.0,61.1,4.9671,2.0,242.0,17.8,392.83,34.7
3.0,LOW,0.0,2.18,NO,458.0,6998.0,45.8,6.0622,3.0,222.0,18.7,394.63,33.4
4.0,LOW,0.0,2.18,NO,458.0,7147.0,54.2,6.0622,3.0,222.0,18.7,396.90,36.2

In [29]:
df_drop.isna().sum()

CRIM       0
ZN         1
INDUS      2
CHAS       0
NOX        6
RM         2
AGE        1
DIS        2
RAD        0
TAX        0
PTRATIO    3
B          1
PRICE      0
dtype: int64

In [30]:
replace_with = df_drop.mean(numeric_only=True)
df_drop = df_drop.fillna(replace_with)
df_drop.head(30)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,PRICE
0.0,LOW,18.000000,2.310000,NO,538.000000,6575.000000,65.2,4.0900,1.0,296.0,15.3,396.90,24.0
1.0,LOW,0.000000,7.070000,NO,469.000000,6421.000000,78.9,4.9671,2.0,242.0,17.8,396.90,21.6
2.0,LOW,0.000000,7.070000,NO,469.000000,7185.000000,61.1,4.9671,2.0,242.0,17.8,392.83,34.7
3.0,LOW,0.000000,2.180000,NO,458.000000,6998.000000,45.8,6.0622,3.0,222.0,18.7,394.63,33.4
4.0,LOW,0.000000,2.180000,NO,458.000000,7147.000000,54.2,6.0622,3.0,222.0,18.7,396.90,36.2
5.0,LOW,0.000000,2.180000,NO,458.000000,6.430000,58.7,6.0622,3.0,222.0,18.7,394.12,28.7
6.0,MODERATE,12.500000,7.870000,NO,524.000000,6012.000000,66.6,5.5605,5.0,311.0,15.2,395.60,22.9
7.0,MODERATE,12.500000,7.870000,NO,524.000000,6172.000000,96.1,5.9505,5.0,311.0,15.2,396.90,27.1
8.0,MODERATE,12.500000,7.870000,NO,524.000000,5631.000000,100.0,6.0821,5.0,311.0,15.2,386.63,16.5
9.0,MODERATE,12.500000,7.870000,NO,524.000000,6004.000000,85.9,6.5921,5.0,311.0,15.2,386.71,18.9
10.0,MODERATE,12.500000,7.870000,NO,524.000000,6377.000000,94.3,6.3467,5.0,311.0,15.2,392.52,15.0
11.0,MODERATE,12.500000,7.870000,NO,524.000000,6009.000000,82.9,6.2267,5.0,311.0,15.2,396.90,18.9
12.0,MODERATE,12.500000,7.870000,NO,524.000000,5889.000000,39.0,5.4509,5.0,311.0,15.2,390.50,21.7
13.0,HIGH,0.000000,8.140000,NO,538.000000,5949.000000,61.8,4.7075,4.0,307.0,21.0,396.90,20.4
14.0,VERY HIGH,11.495984,11.146217,NO,463.278693,5626.758853,84.5,4.4619,4.0,307.0,21.0,380.02,18.2
15.0,HIGH,0.000000,8.140000,NO,538.000000,5834.000000,56.5,4.4986,4.0,307.0,21.0,395.62,19.9
16.0,HIGH,0.000000,8.140000,NO,538.000000,5935.000000,29.3,4.4986,4.0,307.0,21.0,386.85,23.1
17.0,HIGH,0.000000,8.140000,NO,538.000000,5.990000,81.7,4.2579,4.0,307.0,21.0,386.75,17.5
18.0,HIGH,0.000000,8.140000,NO,538.000000,5456.000000,36.6,3.7965,4.0,307.0,21.0,288.99,20.2
19.0,HIGH,0.000000,8.140000,NO,538.000000,5727.000000,69.5,3.7965,4.0,307.0,21.0,390.95,18.2
20.0,HIGH,0.000000,8.140000,NO,538.000000,5.570000,98.1,3.7979,4.0,307.0,21.0,376.57,13.6
21.0,HIGH,0.000000,8.140000,NO,538.000000,5965.000000,89.2,4.0123,4.0,307.0,21.0,392.53,19.6
22.0,HIGH,0.000000,8.140000,NO,538.000000,6142.000000,91.7,3.9769,4.0,307.0,21.0,396.90,15.2
23.0,HIGH,0.000000,8.140000,NO,538.000000,5813.000000,100.0,4.0952,4.0,307.0,21.0,394.54,14.5
24.0,HIGH,0.000000,8.140000,NO,538.000000,5924.000000,94.1,4.3996,4.0,307.0,21.0,394.33,15.6
25.0,HIGH,0.000000,8.140000,NO,538.000000,5599.000000,85.7,4.4546,4.0,307.0,21.0,303.42,13.9
26.0,HIGH,0.000000,8.140000,NO,538.000000,5813.000000,90.3,4682.0000,4.0,307.0,21.0,376.88,16.6
27.0,HIGH,0.000000,8.140000,NO,538.000000,6047.000000,88.8,4.4534,4.0,307.0,21.0,306.38,14.8
28.0,HIGH,0.000000,8.140000,NO,538.000000,6495.000000,94.4,4.4547,4.0,307.0,21.0,387.94,18.4
29.0,HIGH,0.000000,8.140000,NO,538.000000,6674.000000,87.3,4239.0000,4.0,307.0,21.0,380.23,21.0

In [31]:
df_drop.isna().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
PRICE      0
dtype: int64

In [32]:
df_drop["CRIM"].unique()

<StringArray>
['LOW', 'MODERATE', 'HIGH', 'VERY HIGH']
Length: 4, dtype: str

In [33]:
df_drop["CRIM"] = df_drop["CRIM"].map({"LOW": 1, "MODERATE": 2, "HIGH": 3, "VERY HIGH": 4})
df_drop.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,PRICE
0.0,1,18.0,2.31,NO,538.0,6575.00,65.2,4.0900,1.0,296.0,15.3,396.90,24.0
1.0,1,0.0,7.07,NO,469.0,6421.00,78.9,4.9671,2.0,242.0,17.8,396.90,21.6
2.0,1,0.0,7.07,NO,469.0,7185.00,61.1,4.9671,2.0,242.0,17.8,392.83,34.7
3.0,1,0.0,2.18,NO,458.0,6998.00,45.8,6.0622,3.0,222.0,18.7,394.63,33.4
4.0,1,0.0,2.18,NO,458.0,7147.00,54.2,6.0622,3.0,222.0,18.7,396.90,36.2
5.0,1,0.0,2.18,NO,458.0,6.43,58.7,6.0622,3.0,222.0,18.7,394.12,28.7
6.0,2,12.5,7.87,NO,524.0,6012.00,66.6,5.5605,5.0,311.0,15.2,395.60,22.9
7.0,2,12.5,7.87,NO,524.0,6172.00,96.1,5.9505,5.0,311.0,15.2,396.90,27.1
8.0,2,12.5,7.87,NO,524.0,5631.00,100.0,6.0821,5.0,311.0,15.2,386.63,16.5
9.0,2,12.5,7.87,NO,524.0,6004.00,85.9,6.5921,5.0,311.0,15.2,386.71,18.9

In [34]:
df_drop["CRIM"].unique()

array([1, 2, 3, 4])

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
le = LabelEncoder()
le.fit(df_drop.CRIM)
df_drop["categorical_label"] = le.transform(df_drop.CRIM)

In [38]:
df_drop["CHAS"].unique()

<StringArray>
['NO', 'YES']
Length: 2, dtype: str

In [39]:
le = LabelEncoder()
df_drop["CHAS"] = le.fit_transform(df_drop["CHAS"])
df_drop.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,PRICE,categorical_label
0.0,1,18.0,2.31,0,538.0,6575.0,65.2,4.0900,1.0,296.0,15.3,396.90,24.0,0
1.0,1,0.0,7.07,0,469.0,6421.0,78.9,4.9671,2.0,242.0,17.8,396.90,21.6,0
2.0,1,0.0,7.07,0,469.0,7185.0,61.1,4.9671,2.0,242.0,17.8,392.83,34.7,0
3.0,1,0.0,2.18,0,458.0,6998.0,45.8,6.0622,3.0,222.0,18.7,394.63,33.4,0
4.0,1,0.0,2.18,0,458.0,7147.0,54.2,6.0622,3.0,222.0,18.7,396.90,36.2,0

In [40]:
df_drop["CHAS"].unique()

array([0, 1])

In [41]:
# standardizzazione - vedi a quali colonne applicarla

df_std = df_drop.copy()

In [43]:
df_std.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,PRICE,categorical_label
count,499.000000,499.000000,499.000000,499.00000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000
mean,2.501002,11.495984,11.146217,0.07014,463.278693,5626.758853,68.465663,383.624881,9.605210,409.060120,18.471976,356.691145,22.498196,1.501002
std,1.123632,23.438782,6.865424,0.25564,223.381611,2007.522873,28.227111,1275.700753,8.753109,169.392312,2.147970,91.569300,9.176405,1.123632
min,1.000000,0.000000,0.460000,0.00000,0.400000,4.880000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,5.000000,0.000000
25%,1.000000,0.000000,5.160000,0.00000,428.000000,5736.000000,44.700000,2.115300,4.000000,279.000000,17.400000,375.270000,16.900000,0.000000
50%,3.000000,0.000000,9.690000,0.00000,499.000000,6127.000000,77.300000,3.495200,5.000000,330.000000,19.100000,391.340000,21.200000,2.000000
75%,3.500000,12.500000,18.100000,0.00000,605.000000,6541.500000,94.050000,6.084900,24.000000,666.000000,20.200000,396.235000,25.000000,2.500000
max,4.000000,100.000000,27.740000,1.00000,871.000000,8725.000000,100.000000,8344.000000,24.000000,711.000000,22.000000,396.900000,50.000000,3.000000

In [44]:
from sklearn.preprocessing import StandardScaler

cols_to_exclude = ['PRICE', 'CHAS', 'categorical_label']
cols_to_scale = [c for c in df_std.columns if c not in cols_to_exclude]

scaler = StandardScaler()
df_std[cols_to_scale] = scaler.fit_transform(df_std[cols_to_scale])

 standardizzi i numeri che misurano "quanto" (tassi, percentuali, distanze, importi), non quelli che indicano "che categoria" (0/1 o etichette), e mai il target insieme alle feature.

In [45]:
features = ["CRIM", "ZN", "INDUS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX", "PTRATIO", "B"]

In [46]:
to_std = df_std[features]


df_std[features] = (to_std - to_std.mean()) / to_std.std()
df_std.head(10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,PRICE,categorical_label
0.0,-1.335848,0.277490,-1.287061,0,0.334501,0.472344,-0.115692,-0.297511,-0.983103,-0.667445,-1.476732,0.439108,24.0,0
1.0,-1.335848,-0.490468,-0.593731,0,0.025612,0.395632,0.369657,-0.296823,-0.868858,-0.986232,-0.312842,0.439108,21.6,0
2.0,-1.335848,-0.490468,-0.593731,0,0.025612,0.776201,-0.260943,-0.296823,-0.868858,-0.986232,-0.312842,0.394661,34.7,0
3.0,-1.335848,-0.490468,-1.305996,0,-0.023631,0.683051,-0.802975,-0.295965,-0.754613,-1.104301,0.106158,0.414319,33.4,0
4.0,-1.335848,-0.490468,-1.305996,0,-0.023631,0.757272,-0.505389,-0.295965,-0.754613,-1.104301,0.106158,0.439108,36.2,0
5.0,-1.335848,-0.490468,-1.305996,0,-0.023631,-2.799634,-0.345967,-0.295965,-0.754613,-1.104301,0.106158,0.408749,28.7,0
6.0,-0.445877,0.042836,-0.477205,0,0.271828,0.191899,-0.066095,-0.296358,-0.526123,-0.578894,-1.523287,0.424912,22.9,1
7.0,-0.445877,0.042836,-0.477205,0,0.271828,0.271599,0.979000,-0.296052,-0.526123,-0.578894,-1.523287,0.439108,27.1,1
8.0,-0.445877,0.042836,-0.477205,0,0.271828,0.002113,1.117165,-0.295949,-0.526123,-0.578894,-1.523287,0.326953,16.5,1
9.0,-0.445877,0.042836,-0.477205,0,0.271828,0.187914,0.617645,-0.295550,-0.526123,-0.578894,-1.523287,0.327827,18.9,1

In [47]:
round(df_std[cols_to_scale].describe(), 2)

,CRIM,ZN,INDUS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B
count,497.00,497.00,497.00,497.00,497.00,497.00,497.00,497.00,497.00,497.00,497.00
mean,-0.00,0.00,0.00,0.00,0.00,-0.00,0.00,0.00,0.00,-0.00,0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.33,-0.49,-1.55,-2.07,-2.79,-2.32,-0.30,-0.98,-1.31,-2.73,-3.88
25%,-1.33,-0.49,-0.88,-0.16,0.06,-0.85,-0.30,-0.64,-0.77,-0.50,0.20
50%,0.45,-0.49,-0.21,0.16,0.25,0.31,-0.30,-0.53,-0.47,0.29,0.38
75%,0.45,0.04,1.01,0.63,0.46,0.91,-0.30,1.64,1.51,0.81,0.43
max,1.34,3.77,2.41,1.82,1.54,1.12,6.23,1.64,1.78,1.64,0.44

In [47]:
df_std[features].std()

CRIM       1.0
ZN         1.0
INDUS      1.0
NOX        1.0
RM         1.0
AGE        1.0
DIS        1.0
RAD        1.0
TAX        1.0
PTRATIO    1.0
B          1.0
dtype: float64

In [48]:
df_std[features].mean()

CRIM       1.423933e-16
ZN         6.407700e-17
INDUS     -1.423933e-17
NOX        7.119667e-18
RM         7.119667e-18
AGE       -2.847867e-17
DIS        1.423933e-17
RAD       -5.695733e-17
TAX       -1.139147e-16
PTRATIO   -1.139147e-16
B          4.271800e-17
dtype: float64

In [50]:
df_std.to_csv("housing_cleaned.tsv", sep="\t")