In [47]:
import pandas as pd

In [32]:
BASE_URL = "https://raw.githubusercontent.com/ProfAI/machine-learning-fondamenti/refs/heads/main/datasets/"

IMPORTARE CSV

In [10]:
df = pd.read_csv(BASE_URL + "shirts_example.csv", index_col=0)
df.head()

  taglia  colore  prezzo
0      S  bianco    4.99
1      M  bianco   19.99
2     XL  bianco   12.49
3     XL  bianco   14.99
4      S  bianco   14.99

con index_col si trasforma la prima colonna che dà di default la funzione quando legge i dati e la si trasforma in indice

TSV

In [11]:
df = pd.read_csv(BASE_URL + "shirts_example.tsv", index_col=0, sep= "\t")
df.head()

  taglia  colore  prezzo
0      S  bianco    4.99
1      M  bianco   19.99
2     XL  bianco   12.49
3     XL  bianco   14.99
4      S  bianco   14.99

"\t" è il carattere che indica come separatore "|".
Pandas non fa distinzione tra csv e tsv

JSON

In [ ]:
df = pd.read_json(BASE_URL + "shirts_example.json")
df.head(10)

  taglia  colore  prezzo
0      S  bianco    4.99
1      M  bianco   19.99
2     XL  bianco   12.49
3     XL  bianco   14.99
4      S  bianco   14.99
5      S   verde    7.99
6      M   verde    4.99
7      L   verde   12.49
8     XL  bianco   12.49
9      M   verde   19.99

XML

In [33]:
df = pd.read_xml(BASE_URL + "shirts_example.xml")
df.head(10)

   id taglia  colore  prezzo
0   0      S  bianco    4.99
1   1      M  bianco   19.99
2   2     XL  bianco   12.49
3   3     XL  bianco   14.99
4   4      S  bianco   14.99
5   5      S   verde    7.99
6   6      M   verde    4.99
7   7      L   verde   12.49
8   8     XL  bianco   12.49
9   9      M   verde   19.99

In [16]:
pd.__version__

'3.0.5'

HTML

In [37]:
df = pd.read_html(BASE_URL + "shirts_example.html")
type(df)

list

In [39]:
df = pd.read_html(BASE_URL + "shirts_example.html")
df[0].head()

     0       1       2       3
0  NaN  taglia  colore  prezzo
1  0.0       S  bianco    4.99
2  1.0       M  bianco   19.99
3  2.0      XL  bianco   12.49
4  3.0      XL  bianco   14.99

In [42]:
df = pd.read_html(BASE_URL + "shirts_example.html", index_col=0)
df[0].head()

          1       2       3
0
NaN  taglia  colore  prezzo
0.0       S  bianco    4.99
1.0       M  bianco   19.99
2.0      XL  bianco   12.49
3.0      XL  bianco   14.99

In [45]:
df = pd.read_html(BASE_URL + "shirts_example.html", index_col = 0, header = 0)
df[0].head()

  taglia  colore  prezzo
0      S  bianco    4.99
1      M  bianco   19.99
2     XL  bianco   12.49
3     XL  bianco   14.99
4      S  bianco   14.99

EXCEL

In [48]:
df = pd.read_excel(BASE_URL + "shirts_example.ods")
df.head()

   Unnamed: 0 taglia  colore  prezzo
0           0      S  bianco    4.99
1           1      M  bianco   19.99
2           2     XL  bianco   12.49
3           3     XL  bianco   14.99
4           4      S  bianco   14.99

In [49]:
df = pd.read_excel(BASE_URL + "shirts_example.ods", index_col=0)
df.head()

  taglia  colore  prezzo
0      S  bianco    4.99
1      M  bianco   19.99
2     XL  bianco   12.49
3     XL  bianco   14.99
4      S  bianco   14.99