## Eseguire l'imputazione per i dati mancanti

sostituire i valori mancanti con altri valori

In [1]:
import numpy as np
import pandas as pd

### MEAN IMPUTATION
sostituire con il valore medio per la colonna

In [2]:
BASE_URL = "https://raw.githubusercontent.com/ProfAI/machine-learning-fondamenti/refs/heads/main/datasets/"

In [3]:
iris = pd.read_csv(BASE_URL + "iris_missing.csv")
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          NaN           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          NaN           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [29]:
iris_imp = iris.copy()

verifichiamo quale colonna ha più valori mancanti:

sepal_width     10

In [20]:
col = "sepal_width"

In [21]:
replace_with = round(iris_imp[col].mean(), 1)
replace_with

np.float64(3.1)

In [22]:
iris_imp[col] = iris_imp[col].fillna(replace_with)
iris_imp[col].head()

0    3.1
1    3.0
2    3.2
3    3.1
4    3.6
Name: sepal_width, dtype: float64

In [23]:
iris_imp.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.1           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [24]:
iris_imp.isna().sum()

sepal_length    3
sepal_width     0
petal_length    2
petal_width     0
species         0
dtype: int64

In [25]:
iris_imp[col].median()

np.float64(3.0)

In [27]:
iris_imp[col].mode()[0]

np.float64(3.0)

nel caso della moda, spesso non viene restituito un solo valore ma una serie di valori, per questo si specifica con l'indice quale valore di moda considerare

In [28]:
iris_imp.copy()

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.1           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           NaN          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [33]:
replace_with = iris_imp.mean(numeric_only=True)
iris_imp = round(iris_imp.fillna(replace_with), 1)
iris_imp.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.1           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [34]:
iris_imp.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

#### Si può utilizzare un trasformatore di SciKit-Learn

In [40]:
from sklearn.impute import SimpleImputer

In [38]:
X = iris.drop("species", axis=1).values
X.shape

(150, 4)

In [41]:
imp = SimpleImputer(strategy= "mean")
X_imp = imp.fit_transform(X)
X_imp[:5]

array([[5.1       , 3.05642857, 1.4       , 0.2       ],
       [4.9       , 3.        , 1.4       , 0.2       ],
       [4.7       , 3.2       , 1.3       , 0.2       ],
       [4.6       , 3.05642857, 1.5       , 0.2       ],
       [5.        , 3.6       , 1.4       , 0.2       ]])

In [43]:
np.isnan(X).sum(axis=0)

array([ 3, 10,  2,  0])