## Codifica del target tramite label endocing

In [1]:
import pandas as pd

In [2]:
BASE_URL = "https://raw.githubusercontent.com/ProfAI/machine-learning-fondamenti/refs/heads/main/datasets/"

In [3]:
df = pd.read_csv(BASE_URL + "shirts_sold.csv", index_col=0)
df.head()

  taglia  colore  prezzo venduta
0      S  bianco    4.99      NO
1      M  bianco   19.99      SI
2     XL  bianco   12.49      NO
3     XL  bianco   14.99      NO
4      S  bianco   14.99      SI

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
x = LabelEncoder() #inizializza
df["venduta"] = x.fit_transform(df["venduta"])
df.head()

  taglia  colore  prezzo  venduta
0      S  bianco    4.99        0
1      M  bianco   19.99        1
2     XL  bianco   12.49        0
3     XL  bianco   14.99        0
4      S  bianco   14.99        1

In [6]:
x.classes_

array(['NO', 'SI'], dtype=object)

In [7]:
# se vogliamo invece fare una trasformazione inversa (0,1 -> Vero, Falso)

y = [0, 0, 1, 0, 1]

x.inverse_transform(y)

array(['NO', 'NO', 'SI', 'NO', 'SI'], dtype=object)